name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: hello-world
        run: echo "Hello World! GithubActions works!"
      - name: make-lint
        run: make lint
